### ISSUE TITLE
[Enhancement] Access to create multiple store

### ISSUE THREAD

**Issue by Truongvv10** [TRCStudioDean/GlobalMarketPlus#1]
**Introduction**

> Different players can create multiple stores in the market to be able to organize their store. This opens more possibilities for players to customize their shop with chestsign and organize their shop per category. 

> With the chestsign players can assign which of their own shop goes on that chest. This make it so players can be more interactive with building and decorating their shop when using signs. 

**Commands**

> Some possible commands:
> /store create <name>

**Comment by TRCStudioDean** [comment]
The related functions will be gradually improved in the future, so stay tuned.

**Comment by Truongvv10** [comment]
Looking forward to it.
