### ISSUE TITLE
Retaining-Decimal-Places: 0

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/GlobalMarketPlus#10]
![image](https://github.com/TRCStudioDean/GlobalMarketPlus/assets/68499464/90f47bd1-b4b2-4a5c-b007-f584cec4a386)
Retaining-Decimal-Places: 0 應該要把` . `去除，因為沒有小數了

**Comment by TRCStudioDean** [comment]
1.2.3.0 修復完成
