### ISSUE TITLE
{displayBalance} 佔位符部分不顯示

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/GlobalMarketPlus#11]
我將插件中全部的 {Balance} 替換成 {displayBalance}
發現有些 {Balance} 會顯示的值在 {displayBalance} 不顯示
![餘額新增訊息](https://cdn.discordapp.com/attachments/1149011812440871042/1165595420320346183/image.png?ex=65476c53&is=6534f753&hm=a695e885241e9421117e67e3aa66235d43ba4c4e9a11a705bb77b86be51c3ea2&)

可能還有其他的 佔位符 不正常顯示，但這是其中一個
插件版本：1.2.2.0

**Comment by RICE0707** [comment]
補充：
有些地方是可以正常顯示的，例如` /gmp money info `
![](https://cdn.discordapp.com/attachments/1078953176729915443/1165506405281833030/image.png?ex=6547196d&is=6534a46d&hm=e40c8c196c176b51ee67b93ec1b081316908c3274b4b70504a7d314ecefb1d89&)

**Comment by RICE0707** [comment]
補充：
我剛剛看到了在更新說明中的
```
此版本變更了 Messages.yml 中的餘額顯示設定和一些 GUISettings。
需要手動新增或刪除設定檔來自動產生更新到最新的顯示效果！
```
資訊，想請問一些具體改動了哪些訊息的內容，
（由於我幾乎改動了全部的 Messages 與 GUI 顯示文字，所以直接刪除的話可能不太合適 ....）

**Comment by TRCStudioDean** [comment]
1.2.3.0 修復完成
