### ISSUE TITLE
Cant connect to global market.

### ISSUE THREAD

**Issue by Foxbait** [TRCStudioDean/GlobalMarketPlus#16]
I'd like to play solo but still connected to global market. If you could help me out that be great.

It says I can upload to the market but when I open the market up, I see no items from other users that use the plugin. Stated multiserver in the spigot plugin site. 

Is this plugin on my server am I connected to a global market server? Or is it only for hosted server only?

**Comment by TRCStudioDean** [comment]
You just need to ensure that this plugin can access the internet normally, at least not block the address of spigotmc.

**Comment by Foxbait** [comment]
Can you give me a tutorial on how to access the internet with the plugin?

**Comment by Foxbait** [comment]
It says successfully enabled in server log but i don't see any items in the store. I assume there would be items and im the only player on my server.

**Comment by TRCStudioDean** [comment]
Can you show me some screenshots about this situation?

**Comment by TRCStudioDean** [comment]
I think we may not be talking about the same thing

**Comment by Foxbait** [comment]
Is this plugin connect to a market server? or is it only just within the server? 

Ican't give a screenshot as my issue is if it is a plugin that connects to a market server for multiple servers using the plugin.
