### ISSUE TITLE
After I test some commands, I can't use it. Please look error and help me.

### ISSUE THREAD

**Issue by OatOSV** [TRCStudioDean/GlobalMarketPlus#21]
![Screenshot 2024-07-26 190646](https://github.com/user-attachments/assets/59987ea4-37f3-47e6-a3a3-c4bcc67bbbb0)

**Comment by TRCStudioDean** [comment]
Before providing assistance, we would like you to provide us with your SpigotMC account nickname so that we can determine if you have purchased this plugin. We only provide assistance to users who have purchased plugins.
