### ISSUE TITLE
拍賣功能結算合理化

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/GlobalMarketPlus#5]
希望當拍賣被喊價後，會增加拍賣的剩餘秒數（可配置增加多少、最多總時長可被增加至多少 .. 等），
避免文玩家壓秒喊價的情況產生。

**Comment by TRCStudioDean** [comment]
此功能已在1.1.6.0版本中更新過，請在GlobalMarket.yml中進行設定。
