### ISSUE TITLE
內部站位符顯示錯誤

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/GlobalMarketPlus#6]
![](https://cdn.discordapp.com/attachments/596718421966716928/1164299678402220072/Screenshot_20231019_043049_Discord.png?ex=6542b592&is=65304092&hm=e90fcdbc448eab99470ed31fc2d99995aa2ffd5aa299487622b15e1ada71db27&)

**Comment by TRCStudioDean** [comment]
此設定已于1.2.0.0更新中修復，你需要手動更新Messages.yml或刪除等待重新生成。
