### ISSUE TITLE
Auction-Automatic-Overtime 的 {topBidder} 內部佔位符顯示錯誤

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/GlobalMarketPlus#7]
![image](https://github.com/TRCStudioDean/GlobalMarketPlus/assets/68499464/6b475a78-6fa5-4eca-97e5-c231664c16a0)

` {prefix}&a玩家 &d{topBidder} &a已觸發到&e拍賣限制規則&7（&e{policy}&7）&a，故該拍賣的剩餘時間增加了 &c{overtime} &a。 `
其中` {topBidder}  `的部份顯示為` 0 `，而非最高出價者。

插件使用版本：1.2.1.2

**Comment by TRCStudioDean** [comment]
我沒有找到對應的問題所在，所有佔位符顯示都是正常的

**Comment by RICE0707** [comment]
最新版本測試後沒有這個問題了。
