### ISSUE TITLE
希望玩家可以關閉、開啟讀取拍賣喊價訊息

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/GlobalMarketPlus#8]
拍賣訊息十分洗版，希望可以有這個功能，
可能當玩家關閉後，只會顯示` 拍賣的上架訊息 `與` 成交訊息這樣 `，
或者直接細化，讓玩家可用指令 Tab 選擇` 關閉、開啟 `讀取` 拍賣喊價訊息、拍賣上架訊息、拍賣成交訊息 `
（如果有指令 Tab 的話，希望可以定義 Tab 的選項）

**Comment by TRCStudioDean** [comment]
這個功能由於本插件的訊息發送系統設定原因，無法實現，只有推翻重做才能夠實現
